#------------
#INPUT SELECT
#------------
#
#
#
input_select:
  clack_water_softener_status:
    name: Water softener status
    options:
      - Backwash
      - Brine
      - Backwash2
      - Rinse
      - Fill
      - Idle
    initial: Idle

input_boolean:
  brine_almost_finished:
    name: Brine Almost Finished
    initial: off
    icon: mdi:timer-sand
  clack_manual_regen:
    name: Clack Manual Regen
    initial: off
    icon: mdi:water-pump-off

input_number:
  brine_alert_time:
    name: Brine Alert Time Before Finish
    initial: 5
    min: 1
    max: 10
    step: 1
    unit_of_measurement: 'minutes'
    icon: mdi:timer-outline
        
#-----------
#TIMERS
#-----------
# Remark: change the timer settings, upon your own timing (measure time with stopwatch on the complet regen. cycle)
timer:
  timer_ws_backwash:
    name: Backwash
    #duration: '0:02:10'  
    duration: '0:01:00' #original

  timer_ws_brine:
    name: Brine
    #duration: '0:57:16'
    duration: '0:30:00' #original

  timer_ws_backwash2:
    name: Backwash2
#    duration: '0:00:57'
    duration: '0:02:00'

  timer_ws_rinse:
    name: Rinse
    #duration: '0:03:05'
    duration: '0:02:00' #original

  timer_ws_fill:
    name: Fill
    #duration: '0:04:55'
    duration: '0:02:00' #original

  timer_ws_total:  #sum of all above values
    name: Total
    #duration: '1:07:26'
    duration: '0:37:00' #orginal

#-----------
#SENSORS
#-----------
template:
  sensor:
    - name: "time_to_regeneration" # custom sensor that calculates the expected number of days till the next regeneration
      state: >
        {%- set time = (states('number.clack_capacity_in_days') | int * 86400) - (as_timestamp(now()) - as_timestamp((strptime(states('sensor.clack_regenerated_on')[4:15], '%d %b %H:%M').replace(year=now().year)))) | int  %}
        {%- set hours = ((time % 86400) // 3600) %}
        {%- set hours = '{}h '.format(hours) if hours > 0 else '' %}
        {%- set days = (time // 86400) %}
        {%- set days = '{}d '.format(days) if days > 0 else '' %}
        {{days + hours}}
      unique_id: "time_to_regeneration"
      icon: mdi:calendar-clock

#-----------
#UTILITY METER
#-----------
utility_meter:
  clack_waterusage_this_quarter:  
    source: sensor.clack_water_meter
    cycle: quarter-hourly
  clack_waterusage_this_hour:
    source: sensor.clack_water_meter
    cycle: hourly
  clack_waterusage_today:
    source: sensor.clack_water_meter
    cycle: daily 
  clack_waterusage_this_month:
    source: sensor.clack_water_meter
    cycle: monthly
  clack_waterusage_this_year:
    source: sensor.clack_water_meter
    cycle: yearly 

automation:
  ####################################################
  - id: set_water_softener_start_backwash
    alias: Set water softener start Backwash
    trigger:
    - platform: state
      entity_id:
      - binary_sensor.clack_regeneration_pulse
      to: 'on'
    - platform: state
      entity_id: button.clack_test_button_regen_pulse
    condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.clack_water_softener_status
        state: Idle
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.clack_water_softener_status
        option: Backwash
    - service: timer.start
      entity_id: timer.timer_ws_backwash
    - service: timer.start
      entity_id: timer.timer_ws_total
    initial_state: true
  ####################################################
  - id: set_water_softener_start_brine
    alias: Set water softener start Brine
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_ws_backwash
    condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.clack_water_softener_status
        state: Backwash
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.clack_water_softener_status
        option: Brine
    - service: timer.start
      entity_id: timer.timer_ws_brine
    initial_state: true
  ####################################################
  - id: set_water_softener_start_backwash2
    alias: Set water softener start Backwash2
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_ws_brine
    condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.clack_water_softener_status
        state: Brine
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.clack_water_softener_status
        option: Backwash2
    - service: timer.start
      entity_id: timer.timer_ws_backwash2
    initial_state: true
  ####################################################
  - id: set_water_softener_start_rinse
    alias: Set water softener start Rinse
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_ws_backwash2
    condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.clack_water_softener_status
        state: Backwash2
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.clack_water_softener_status
        option: Rinse
    - service: timer.start
      entity_id: timer.timer_ws_rinse
    initial_state: true
  ####################################################
  - id: set_water_softener_start_fill
    alias: Set water softener start Fill
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_ws_rinse
    condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.clack_water_softener_status
        state: Rinse
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.clack_water_softener_status
        option: Fill
    - service: timer.start
      entity_id: timer.timer_ws_fill
    initial_state: true
  ####################################################
  - id: set_water_softener_idle
    alias: Set water softener Idle
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_ws_fill
    condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.clack_water_softener_status
        state: Fill
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.clack_water_softener_status
        option: Idle
    - service: esphome.clack_meterstand_clack
      data:
        meter_value: 0
    - service: input_number.set_value
      data_template:
        entity_id: input_number.clack_water_softener_meter_liters
        value: 0
    initial_state: true
  #------------------------------------------------------------------
  # Extra options: Salt level alarm and hardness measurement alarm. 
  # Fill in your own mobile_app_iphone_van_xxx in. (as an example)            
  #------------------------------------------------------------------
  - id: salt_level_alarm_notify
    alias: Salt level alarm notify
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.clack_fill_salt
      to: "yes"
    condition:
    - condition: time
      after: 07:30:00
      before: '22:00:00'
    action:
    - service: notify.mobile_app_iphone_van_a_c_a
      data:
        title: Be aware!
        message: Salt level watersoftener is low! Fill salt today!
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1
    - delay:
        minutes: 30
    initial_state: 'true'
    mode: single
################################################
  - id: brine_almost_finished_alert
    alias: "Softener - Brine Almost Finished Alert"
    description: "Sets the input boolean to on when the brine timer is X minutes before it ends, and turns it off when the timer is done."
    trigger:
      - platform: template
        value_template: >
          {% set finish_time = state_attr('timer.timer_ws_brine', 'finishes_at') %}
          {% set remaining_seconds = '00:00:00' if finish_time is none else (as_datetime(finish_time) - now()).total_seconds() %}
          {% set alert_time_seconds = (states('input_number.brine_alert_time') | int) * 60 %}
          {{ remaining_seconds > 0 and remaining_seconds <= alert_time_seconds }}
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_ws_brine
    condition: []
    action:
      - choose:
          - conditions: 
              - condition: template
                value_template: "{{ trigger.platform == 'template' }}"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.brine_almost_finished
              - service: esphome.Clack_set_brine_almost_finished
                data:
                  state: true
          - conditions:
              - condition: template
                value_template: "{{ trigger.platform == 'event' }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.brine_almost_finished
              - service: esphome.Clack_set_brine_almost_finished
                data:
                  state: false
    mode: single
################################################
  - id: 'clack_manual_regen_control'
    alias: "Softener - Clack Manual Regen Control"
    description: "Automates the Clack chlorinator for manual regen and auto-off."
    trigger:
      - platform: state
        entity_id: input_boolean.clack_manual_regen
        to: 'on'
      - platform: state
        entity_id: input_boolean.clack_manual_regen
        to: 'off'
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.clack_manual_regen
                state: 'on'
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.clack_chlorinator
              - delay:
                  minutes: 2
                  seconds: 5
              - service: switch.turn_off
                target:
                  entity_id: switch.clack_chlorinator
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.clack_manual_regen
          - conditions:
              - condition: state
                entity_id: input_boolean.clack_manual_regen
                state: 'off'
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.clack_chlorinator
    mode: restart
